name: release cn

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 3.2.0)'
        required: true
        default: '3.2.0'
        type: string

env:
  VERSION: ${{ github.event.inputs.version }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Assemble Artifacts
        run: |
          ./gradlew assembleRelease

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_apk
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEY_STORE }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "36.0.0"

      - name: Rename APK
        run: |
          mv ${{steps.sign_apk.outputs.signedReleaseFile}} app/build/outputs/apk/release/look4sat_${VERSION}_tle_cn.apk

      - name: Create Release and Upload APK
        run: |
          RELEASE_TITLE="Release v${VERSION}"
          gh release create "v${VERSION}" --title="$RELEASE_TITLE" --generate-notes
          gh release upload "v${VERSION}" app/build/outputs/apk/release/look4sat_${VERSION}_tle_cn.apk